config/routes.rb
Egg2::Application.routes.draw do
  root 'static_pages#home'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :users
  
  resources :invites
  resources :memberships
  resources :sessions, only: [:new, :create, :destroy]
  resources :inputs
 
  resources :groups do
    resources :products, shallow: true
  end

  resources :groups do
    resources :dash, shallow: true
  end

  resources :groups do
    resources :inputs, shallow: true
  end

  resources :groups do
    resources :outputs, shallow: true
  end

  resources :groups do
    resources :customers
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_and_belongs_to_many :product  
  belongs_to :group

  validates :customer_area, length: { is: 0 }, length: { is: 3 }, allow_blank: true, numericality: true
  validates :customer_phone, length: { is: 0}, length: { is: 7}, allow_blank: true, numericality: true

  def human_readable_phone_number
    unless customer_phone.nil? && customer_area.nil?
      "(#{ self.customer_area }) #{ self.customer_phone.first(3)}-#{ self.customer_phone.last(4) }"
    else
      ""
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :products
  has_many :inputs
  has_many :outputs
  has_many :customers
end

app/models/input.rb
class Input < ActiveRecord::Base
  belongs_to :product
  belongs_to :group
  validates :quantityof, allow_blank: false, numericality: true
  def formatted_time
    input_time.strftime("%b %e")
  end
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  def invitee_email
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/output.rb
class Output < ActiveRecord::Base
  belongs_to :customers
  belongs_to :product
  belongs_to :group
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :group
  has_many :inputs
  has_many :customers
  has_many :outputs

  validates :description, length: { maximum: 250}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base

  has_secure_password

  before_save { self.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }
  validates :password_confirmation, presence: true
  validates :area_code, length: { is: 0 }, length: { is: 3 }, allow_blank: true, numericality: true
  validates :phone_number, length: { is: 0}, length: { is: 7}, allow_blank: true, numericality: true
 





  has_many :memberships
  has_many :groups, through: :memberships

  def human_readable_phone_number
    unless phone_number.nil? && area_code.nil?
      "(#{ self.area_code }) #{ self.phone_number.first(3)}-#{ self.phone_number.last(4) }"
    else
      ""
    end
  end
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/dash_controller.rb
class DashController < ApplicationController
  def index
    @user = User.find_by_email(params[:email])
    @group = Group.find(params[:group_id])    
    @all_group_products = Product.where(group_id: params[:group_id])
    @input = Input.where(product_id: params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @all_group_products = Product.where(group_id: params[:group_id])
    @group = Group.where(user_id: params[:user_id])
    if @group.nil?
      then 
      redirect_to new_group_path
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      Membership.create(group_id: @group.id, user_id: current_user.id)
      flash[:success] = "Group Created"
      redirect_to @group
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
    @invite = Invite.new
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = "Group Updated"
      redirect_to @group
    else
      render 'edit'
    end
  end

  private

    def group_params
      params.require(:group).permit(:name)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dash_helper.rb
module DashHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<h1>Edit <%= Group.find(params[:id]).name %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@group) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Update group", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@invite) do |f| %>

      <%= hidden_field_tag(:group_id, params[:id]) %>

      <%= f.label :email_to_invite %>
      <%= f.text_field :invitee_email %>

      <%= f.submit "Invite User", class: "btn btn-large" %>
    <% end %>
  </div>

  
</div>

app/views/groups/index.html.erb
<h1>All Groups for <%= current_user.name %></h1>

<div class="row">

  <div class="span8 offset3">
      <% current_user.groups.each do |grp| %>
		<b><%= grp.name.capitalize %></b>
      <p><%= link_to "Members", group_path(grp), class: "btn btn-large" %> -
      <%= link_to "Inventory", group_products_path(grp), class: "btn btn-large"  %> -
       <%= link_to "Dashboard", group_dash_index_path(grp), class: "btn btn-large" %> 
        <br>
      <br>
    <% end %>
  </div>
</div>

<div class="center_button">
  <% if current_user.groups.empty? %>
    <h3>Looks like you're not part of a group yet.</h3>
    <%= link_to "Create a group!", new_group_path, class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/groups/new.html.erb
<h1>Create a new group</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@group) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create group", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<h1>Groups Page for <%= Group.find(params[:id]).name %></h1>

<div class="row">
  <div class="span6 offset3">
    <h2>Group members</h2>
    <% Group.find(params[:id]).users.each do |usr| %>
      <li><%= usr.name.capitalize %> <%= "- #{usr.human_readable_phone_number}" unless usr.human_readable_phone_number.empty? %> </li>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span6 offset3">
    <%= link_to "Edit Group", edit_group_path, class: "pull-right" %><br><br> 

    <h2>Company members</h2>
  </div>
</div>