config/routes.rb
Egg2::Application.routes.draw do
  root 'static_pages#home'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :users
  
  resources :invites
  resources :memberships
  resources :sessions, only: [:new, :create, :destroy]
  resources :inputs
 
  resources :groups do
    resources :products, shallow: true
  end

  resources :groups do
    resources :dash, shallow: true
  end

  resources :groups do
    resources :inputs, shallow: true
  end

  resources :groups do
    resources :outputs, shallow: true
  end

  resources :groups do
    resources :customers
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_and_belongs_to_many :product  
  belongs_to :group

  validates :customer_area, length: { is: 0 }, length: { is: 3 }, allow_blank: true, numericality: true
  validates :customer_phone, length: { is: 0}, length: { is: 7}, allow_blank: true, numericality: true

  def human_readable_phone_number
    unless customer_phone.nil? && customer_area.nil?
      "(#{ self.customer_area }) #{ self.customer_phone.first(3)}-#{ self.customer_phone.last(4) }"
    else
      ""
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :products
  has_many :inputs
  has_many :outputs
  has_many :customers
end

app/models/input.rb
class Input < ActiveRecord::Base
  belongs_to :product
  belongs_to :group
  validates :quantityof, allow_blank: false, numericality: true
  def formatted_time
    input_time.strftime("%b %e")
  end
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  def invitee_email
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/output.rb
class Output < ActiveRecord::Base
  belongs_to :customers
  belongs_to :product
  belongs_to :group
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :group
  has_many :inputs
  has_many :customers
  has_many :outputs

  validates :description, length: { maximum: 250}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base

  has_secure_password

  before_save { self.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }
  validates :password_confirmation, presence: true
  validates :area_code, length: { is: 0 }, length: { is: 3 }, allow_blank: true, numericality: true
  validates :phone_number, length: { is: 0}, length: { is: 7}, allow_blank: true, numericality: true
 





  has_many :memberships
  has_many :groups, through: :memberships

  def human_readable_phone_number
    unless phone_number.nil? && area_code.nil?
      "(#{ self.area_code }) #{ self.phone_number.first(3)}-#{ self.phone_number.last(4) }"
    else
      ""
    end
  end
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/dash_controller.rb
class DashController < ApplicationController
  def index
    @user = User.find_by_email(params[:email])
    @group = Group.find(params[:group_id])    
    @all_group_products = Product.where(group_id: params[:group_id])
    @input = Input.where(product_id: params[:group_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @all_group_products = Product.where(group_id: params[:group_id])
    @group = Group.find(params[:group_id])
  end

  def show
    @product = Product.find(params[:id])
    @product.group_id = params[:group_id]
  end

  def new
    @group = Group.find(params[:group_id])
    @product = Product.new

  end

  def create
    @group = Group.find(params[:group_id])
    @product = Product.new(product_params)
    @product.group_id = params[:group_id]
    if @product.save
      flash[:success] = "New product added."
      redirect_to group_products_path(@group)
    else
      flash[:error] = "Description should be less than 250 characters"
      redirect_to new_group_product_path
    end
  end

  def edit
    
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = "Product changed"
    redirect_to group_products_path(@product.group)
    else
      flash[:error] = "Description should be less than 250 characters"
      redirect_to edit_product_path
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @group = @product.group
    @product.destroy
    flash[:success] = "Product removed from inventory."
    redirect_to group_products_path(@group)
  end

  private

    def lowinv
      @product = Product.find(params[:id])
      if @product.numberofproduct < @product.minimumnum
  end 

  def lowinv2
    @product = Product.find(params[:id])
    @t = Time.now
    @t2 = @t.beginning_of_day
    @t3 = @t2 + 19.hours + 10.minutes
    if @t3 and lowinv
      then 
      @product.send_lowinventory_email
    end
  end end
    

  def product_params
    params.require(:product).permit(:name, :group_id, :description, :numberofproduct, :minimumnum)
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dash_helper.rb
module DashHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for [@group, @product] do |f| %>


      <%= f.label :name %>
      <%= f.text_field :name %>
<br>
<br>
 
      <%= f.label :description %>  <font size="2"><li class="divider"> should be less than 250 characters</li></font>
      <%= f.text_field :description %>
	
      <%= f.submit "Edit product", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
Product Inventory
<div class="center_button">
    <%= link_to "Add a product!", new_group_product_path(@group), class: "btn btn-large btn-primary" %>
 
</div>

<div class = "row">
 	<div class="span8 offset3"><br>


	</div>
</div>
<% unless @all_group_products.empty? %>
  <% @all_group_products.each do |product| %>

  <table border="1">
  	<tr>
  		<td>Product Name</td><td> Description</td><td>Current Quantity</td><td>Minimum Quantity</td>
  	</tr>
  	<tr>
  		<td><%= product.name %></td><td><%= product.description %></td><td><%= product.numberofproduct %></td><td><%= product.minimumnum %></td>
  </table>
    	 <%= link_to "Edit", edit_product_path(product) %> - <%= link_to "Remove", product_path(product), :method => :delete, :confirm => "Are you sure you want to delete this?" %><br><br>

  <% end %>
<% else %>
  <h3>Looks like you do not have a product yet.</h3>
<% end %>

app/views/products/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for [@group, @product] do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :model_number %>
      <%= f.text_field :model %>

      <%= f.label :description %>
      <%= f.text_field :description %>
	
			<%= f.label :minimum_number_of_this_product %>
			*This will email you when it gets below this number*
      <%= f.text_field :minimumnum  %>


      <%= f.submit "Add product", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>